### ISSUE TITLE
numba and numpy

### ISSUE THREAD

**Issue by windytong** [AlbertGBena/RaProM#1]
When I run the program, I find that numba and numpy versions conflict, I try to upgrade or reduce the version, but still can not resolve. May I ask Professor, which version of numba and numpy do you use here?

**Comment by AlbertGBena** [comment]
Dear Windytong, 
could you send me the error message when you execute RaProM with numba?

**Comment by windytong** [comment]
Wow, I'm so excited to hear from you. Teacher, now I can run the program, I do not know why there are many files missing and other problems, I also used the Python CorrecRawFiles-py 38.py-h1851 command, can solve most of the problems, but there are still some files failed. In the attachment, I have sent a raw data that cannot be solved. Please kindly help me look at it. I look forward to hearing from my teacher again




tongroc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlbertGBena/RaProM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月18日(星期四) 下午3:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AlbertGBena/RaProM] numba and numpy (Issue #1)





 
Dear Windytong,
 could you send me the error message when you execute RaProM with numba?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

0808.raw (163.00M, 2024年08月17日 17:58 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=04313461a832e2c2776f3c594530001841450c055553010614530158021d00060d5519005408541a0f02505000010a56580103076338320701010c4f1151453704&code=914ac027

**Comment by AlbertGBena** [comment]
Dear Windytong,
It's very strange because I've executed RaProM, and I havent any problem. The raw file had some mistake (94 lines), but RaProM is capable to correct it. 
I use python 3.9. with numpy version 1.21.5.
I upload the netcdf, in zip file, where the first height is 1851m
[0808-corrected-processed.zip](https://github.com/user-attachments/files/16311715/0808-corrected-processed.zip)

I still don't know what problems he had. Could you detail the problems better?

Albert GB

**Comment by windytong** [comment]
无持续风向
***@***.***



&nbsp;
Dear Albert GB


Sir, I have a few more questions for you.&nbsp;
1. python RaProM XX.py-h100.8, where 100.8 is the altitude? If it is the altitude at which the instrument was installed, is the first level of my data also 1851?&nbsp;
2. When I run python RaProM XX.py, without considering the height, I feel that BBtop and BBbottom are significantly lower than the values observed by other instruments.&nbsp;
3.I have sent my data processing procedures and data to the teacher, and I ask the teacher to give me guidance. Thank you, teacher, and I look forward to receiving your reply.
4.Why is most of my raw data corrupted, is it related to the observation Settings?


Windytong


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlbertGBena/RaProM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月19日(星期五) 晚上8:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AlbertGBena/RaProM] numba and numpy (Issue #1)





 
Dear Windytong,
 It's very strange because I've executed RaProM, and I havent any problem. The raw file had some mistake (94 lines), but RaProM is capable to correct it.
 I use python 3.9. with numpy version 1.21.5.
 I upload the netcdf, in zip file, where the first height is 1851m
 0808-corrected-processed.zip
 
I still don't know what problems he had. Could you detail the problems better?
 
Albert GB
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

data-py.7z (252.50M, 2024年08月18日 21:02 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=09666538519405c578386d001265001a4e12065a550407561b5f53590448040d0f55480e560157180e56075e0c540b5153565d0d346f325157120415441c1c024c6658&code=6fe84e25

**Comment by AlbertGBena** [comment]
Dear Windy tong,
I answer your questions:
1. python RaProM XX.py-h100.8, where 100.8 is the altitude? Yes, in this case the altitued (height over sea level) is 100.8 m
If it is the altitude at which the instrument was installed, is the first level of my data also 1851? In you case you must execute RaProm with this parameter -h1851
3. When I run python RaProM XX.py, without considering the height, I feel that BBtop and BBbottom are significantly lower than the values observed by other instruments--> The height of the device is very important, because the MRR calculte the vertical speed, then RaProM identify the hydrometeor type with the hypotesis of terminal speed, how you know the terminal speed is function of the pressure variation, thus if the altitude isn't correct the BB levels and hydrometeor type will be wrong.
4.I have sent my data processing procedures and data to the teacher, and I ask the teacher to give me guidance. Thank you, teacher, and I look forward to receiving your reply.--> Now I'll read you procedure and I'll answer in the next post.
5.Why is most of my raw data corrupted, is it related to the observation Settings?--> The mistakes in raw data always are due communication bus. In some acases some line is corrupted or the timestamps is repeat, so this lines must be delete to obtain a correct file. But if you want to see the diffrenmce, remember taht RaProM creates a copy of the original file in the folder named "Moved"
Albert GB

**Comment by AlbertGBena** [comment]
Dear Windytong,

I've read your script and it's very interesting.  My advices are:
1. You must include in RaProM executation the height wehre is the MRR2.
2. In your script you use the Rain Rate to classify, that is a good idea but you must sure that the hydrometeor are in liquid phase, so you could use the discrimitation from RaProM.
3. In you code sometimes you use te parameteer _all. attetion this paramenter implies that the hydrometeor is considered in liquid phase, and that's not always true. If you want to evaluate the liquid phase you must use Z, RR, N(d), LWC, without "_all"
4. I think that you are preparing a paper, so remember to cite our work detailed in github.

Best regards
Albert GB

**Comment by windytong** [comment]
无持续风向
***@***.***



Dear Alber GB:

&nbsp; &nbsp; &nbsp; Thanks for the teacher's suggestions. I will refer to this github in my paper, and plan to recommend teachers as reviewers to give me more suggestions.


best regards
windytong


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlbertGBena/RaProM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月22日(星期一) 晚上7:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AlbertGBena/RaProM] numba and numpy (Issue #1)





 
Dear Windytong,
 
I've read your script and it's very interesting.  My advices are:
  
You must include in RaProM executation the height wehre is the MRR2.
 
In your script you use the Rain Rate to classify, that is a good idea but you must sure that the hydrometeor are in liquid phase, so you could use the discrimitation from RaProM.
 
In you code sometimes you use te parameteer _all. attetion this paramenter implies that the hydrometeor is considered in liquid phase, and that's not always true. If you want to evaluate the liquid phase you must use Z, RR, N(d), LWC, without "_all"
 
I think that you are preparing a paper, so remember to cite our work detailed in github.
  
Best regards
 Albert GB

**Comment by AlbertGBena** [comment]
Good luck!
